<?php
/**
 * Copyright © 2016 FireGento e.V.
 * See LICENSE.md bundled with this module for license details.
 */
/**
 * @var $block \FireGento\MageSetup\Block\Price\Details
 */
?>
<?php
$shippingCostUrl = $block->getShippingCostUrl();
$taxRate = $block->getFormattedTaxRate();
?>
<div class="price-details">
    <?php if ($shippingCostUrl && $block->canShowShippingLink()): ?>
        <?php if ($block->getPriceDisplayType() == \Magento\Tax\Model\Config::DISPLAY_TYPE_EXCLUDING_TAX): ?>
            <?php if ($block->isIncludingShippingCosts()): ?>
                <span class="tax-details">
                    <?= $block->escapeHtml(__('Excl. %1 VAT', $taxRate)) ?>
                    <span class="tax-separator">, </span>
                    <span class="shipping-cost-details">
                        <?= /* @noEscape */ __('incl. <a href="%1">Shipping Cost</a>', $shippingCostUrl) ?>
                    </span>
                </span>
            <?php else: ?>
                <span class="tax-details">
                    <?= $block->escapeHtml(__('Excl. %1 VAT', $taxRate)) ?>
                    <span class="tax-separator">, </span>
                    <span class="shipping-cost-details">
                        <?= /* @noEscape */ __('excl. <a href="%1">Shipping Cost</a>', $shippingCostUrl) ?>
                    </span>
                </span>
            <?php endif ?>
        <?php elseif ($block->getPriceDisplayType() == \Magento\Tax\Model\Config::DISPLAY_TYPE_INCLUDING_TAX): ?>
            <?php if ($block->isIncludingShippingCosts()): ?>
                <span class="tax-details">
                    <?= $block->escapeHtml(__('Incl. %1 VAT', $taxRate)) ?>
                    <span class="tax-separator">, </span>
                    <span class="shipping-cost-details">
                        <?= /* @noEscape */ __('incl. <a href="%1">Shipping Cost</a>', $shippingCostUrl) ?>
                    </span>
                </span>
            <?php else: ?>
                <span class="tax-details">
                    <?= $block->escapeHtml(__('Incl. %1 VAT', $taxRate)) ?>
                    <span class="tax-separator">, </span>
                    <span class="shipping-cost-details">
                        <?= /* @noEscape */ __('excl. <a href="%1">Shipping Cost</a>', $shippingCostUrl) ?>
                    </span>
                </span>
            <?php endif ?>
        <?php elseif ($block->getPriceDisplayType() == \Magento\Tax\Model\Config::DISPLAY_TYPE_BOTH): ?>
            <?php if ($block->isIncludingShippingCosts()): ?>
                <span class="tax-details">
                    <?= /* @noEscape */ __('incl. <a href="%1">Shipping Cost</a>', $shippingCostUrl) ?>
                </span>
            <?php else: ?>
                <span class="tax-details">
                    <?= /* @noEscape */ __('excl. <a href="%1">Shipping Cost</a>', $shippingCostUrl) ?>
                </span>
            <?php endif ?>
        <?php endif ?>
    <?php else: ?>
        <?php if ($block->getPriceDisplayType() == \Magento\Tax\Model\Config::DISPLAY_TYPE_EXCLUDING_TAX): ?>
            <span class="tax-details"><?= $block->escapeHtml(__('Excl. %1 VAT', $taxRate)) ?></span>
        <?php elseif ($block->getPriceDisplayType() == \Magento\Tax\Model\Config::DISPLAY_TYPE_INCLUDING_TAX): ?>
            <span class="tax-details"><?= $block->escapeHtml(__('Incl. %1 VAT', $taxRate)) ?></span>
        <?php endif ?>
    <?php endif ?>
</div>
