<?php
/**
 * Copyright © 2016 FireGento e.V.
 * See LICENSE.md bundled with this module for license details.
 */

/**
 * @var $block \FireGento\MageSetup\Block\Imprint\Content
 */
?>
<p><strong><?= $block->escapeHtml($block->getShopName()) ?></strong></p>

<p>
    <?= $block->escapeHtml($block->getCompanyFirst()) ?><br/>
    <?php if (strlen(trim($block->getCompanySecond()))): ?>
        <?= $block->escapeHtml($block->getCompanySecond()) ?><br/>
    <?php endif ?>
    <?= $block->escapeHtml($block->getStreet()) ?><br/>
    <?= $block->escapeHtml($block->getZip()) ?> <?= $block->escapeHtml($block->getCity()) ?>
</p>

<p>
    <?php if (strlen(trim($block->getTelephone()))): ?>
        <?= $block->escapeHtml(__('Telephone')) ?>: <?= $block->escapeHtml($block->getTelephone()) ?>
        <?php if (strlen(trim($block->getTelephoneAdditional()))): ?>
            (<?= $block->escapeHtml($block->getTelephoneAdditional()) ?>)
        <?php endif ?>
        <br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getFax()))): ?>
        <?= $block->escapeHtml(__('Fax')) ?>: <?= $block->escapeHtml($block->getFax()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getWeb()))): ?>
        <?= $block->escapeHtml(__('Web')) ?>:
        <a href="http://<?= $block->escapeHtmlAttr($block->getWeb()) ?>"
           title="<?= $block->escapeHtmlAttr($block->getCompanyFirst()) ?>">
            <?= $block->escapeHtml($block->getWeb()) ?>
        </a><br/>
    <?php endif ?>
    <?= $block->escapeHtml(__('E-Mail')) ?>: <?= /* @noEscape */ $block->getEmail(false) ?>
</p>

<p>
    <?php if (strlen(trim($block->getFinancialOffice()))): ?>
        <?= $block->escapeHtml(__('Financial office')) ?>: <?= $block->escapeHtml($block->getFinancialOffice()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getTaxNumber()))): ?>
        <?= $block->escapeHtml(__('Tax number')) ?>: <?= $block->escapeHtml($block->getTaxNumber()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getVatId()))): ?>
        <?= $block->escapeHtml(__('VAT-ID')) ?>: <?= $block->escapeHtml($block->getVatId()) ?><br/>
    <?php endif ?>
</p>

<p>
    <?php if (strlen(trim($block->getCeo()))): ?>
        <?= $block->escapeHtml(__('CEO')) ?>: <?= $block->escapeHtml($block->getCeo()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getOwner()))): ?>
        <?= $block->escapeHtml(__('Owner')) ?>: <?= $block->escapeHtml($block->getOwner()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getCourt()))): ?>
        <?= $block->escapeHtml(__('Register court')) ?>: <?= $block->escapeHtml($block->getCourt()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getRegisterNumber()))): ?>
        <?= $block->escapeHtml(__('Register number')) ?>: <?= $block->escapeHtml($block->getRegisterNumber()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getBusinessRules()))): ?>
        <?= $block->escapeHtml(__('Reference for business rules')) ?>:
        <?= $block->escapeHtml($block->getBusinessRules()) ?>
    <?php endif ?>
</p>

<p>
    <?php if (strlen(trim($block->getBankAccountOwner()))): ?>
        <?= $block->escapeHtml(__('Account owner')) ?>: <?= $block->escapeHtml($block->getBankAccountOwner()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getBankAccount()))): ?>
        <?= $block->escapeHtml(__('Account')) ?>: <?= $block->escapeHtml($block->getBankAccount()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getBankCodeNumber()))): ?>
        <?= $block->escapeHtml(__('Bank number')) ?>: <?= $block->escapeHtml($block->getBankCodeNumber()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getBankName()))): ?>
        <?= $block->escapeHtml(__('Bank name')) ?>: <?= $block->escapeHtml($block->getBankName()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getSwift()))): ?>
        <?= $block->escapeHtml(__('SWIFT')) ?>: <?= $block->escapeHtml($block->getSwift()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getIban()))): ?>
        <?= $block->escapeHtml(__('IBAN')) ?>: <?= $block->escapeHtml($block->getIban()) ?><br/>
    <?php endif ?>
    <?php if (strlen(trim($block->getClearing()))): ?>
        <?= $block->escapeHtml(__('Clearing')) ?>: <?= $block->escapeHtml($block->getClearing()) ?><br/>
    <?php endif ?>
</p>
